site_name: ECSC 2026
repo_url: https://github.com/attacking-lab/ecsc2026-ad-wiki
site_url: "https://wiki.ad.ecsc2026.de"
validation:
  links:
    absolute_links: "ignore"
theme:
  name: material
  logo: assets/ecsc2026-logo.svg
  favicon: assets/ecsc2026-logo.svg
  font: false
  palette:
    scheme: slate
    primary: black
    accent: magenta
  custom_dir: overrides
  features:
    - navigation.instant
nav:
  - ECSC 2026 A/D: index.md
  - Changelog: changelog.md
  - Game Overview: game.md
  - Team VMs: vms.md
  - Game Network: network.md
  - CTF Platform: platform.md
  - Scoring Formula: scoring.md
  - Rules of Conduct: conduct.md
  - Cheatsheet: cheatsheet.md
  - Contact: contact.md
markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - tables
  - footnotes
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - assets/katex.js
  - assets/scoring_chart.js
  - assets/param_docs.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
extra:
  generator: false
  platform_url: "https://ad.ecsc2026.de"
  homepage: "https://ad.ecsc2026.de"
  scoreboard_url: "https://scoreboard.ad.ecsc2026.de"
  wiki_url: "https://wiki.ad.ecsc2026.de"
  event_url: "https://ecsc2026.de"
  index: /
  site_name_nav: ECSC<br>2026
extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
  - assets/theme.css
  - assets/style.css
plugins:
  - search
  - git-revision-date
  - git-latest-changes
  - macros
  - print-site:
      print_page_basename: flat
      path_to_pdf: "/flat/"
